# Generated by Django 3.1.7 on 2021-04-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userregistrationotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationOtp',
        ),
    ]
