# Generated by Django 3.1.7 on 2021-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_userregistrationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
