# Generated by Django 3.1.7 on 2021-04-07 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210406_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Account_No',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Beneficially_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Branch_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='IFSC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Name_of_Bank',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
