# Generated by Django 3.1.7 on 2021-04-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210407_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='Account_No',
            field=models.IntegerField(default=0),
        ),
    ]
