# Generated by Django 3.1.7 on 2021-04-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210407_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='IFSC',
            new_name='IFSC_Code',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Branch_Address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Google_Pay',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Paytm_No',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Phonepe_No',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='Re_Account_No',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='UPI_ID',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
