# Generated by Django 3.1.7 on 2021-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210407_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='Phonepe_Number',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='PhonePe_Number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='Google_Pay_Number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='Paytm_Number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
