# Generated by Django 3.1.7 on 2021-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210413_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='edu.png', upload_to='profile_pics'),
        ),
    ]
