# Generated by Django 3.1.7 on 2021-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='videopost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('categori', models.CharField(max_length=10)),
            ],
        ),
    ]
